from .activate_app_handler import activate_app_handler
from .editable_tables_handler import editable_tables_handler
from .features_handler import features_handler
from .history_report_handler import history_report_handler
from .refresh_registration_handler import refresh_registration_handler
from .register_app_handler import register_app_handler
from .register_tenant_handler import register_tenant_handler
from .terms_and_conditions_handler import terms_and_conditions_handler
